### ISSUE TITLE
ClassPrivateProperty but it's not a valid type

### ISSUE THREAD

**Issue by brancusi** [machty/ember-concurrency-decorators#25]
Anyone else getting an error like this?

Build Error (broccoli-persistent-filter:Babel > [Babel: ember-concurrency-decorators]) in ember-concurrency-decorators/test-support/in-run-loop.js

You gave us a visitor for the node type ClassPrivateProperty but it's not a valid type

**Comment by buschtoens** [comment]
This is Babel trying to process [`in-run-loop.js`](https://github.com/machty/ember-concurrency-decorators/blob/master/addon-test-support/in-run-loop.js), but failing to do so.

This is not actually a problem of the file, but with the Babel configuration. Some plugin defines an invalid visitor (i.e. not a function) for `ClassPrivateProperty` AST nodes.

It also _seems_ like this is somehow our own config causing the error.

Are you using `yarn`? What's the output of `yarn list --pattern ember-cli-babel`?

Do you have any more addons or Babel plugins installed that might interfere with the transpilation?

**Comment by csprocket777** [comment]
I've just run into this.

```
- broccoliBuilderErrorStack: Error: organizational-network-visualizer/adapters/application.js: You gave us a visitor for the node type "ClassPrivateProperty" but it's not a valid type
    at verify (/home/gitlab-runner/builds/c2QK9cmj/0/digitalization/personal_network_visualization/node_modules/babel-traverse/lib/visitors.js:196:13)
    at Object.explode (/home/gitlab-runner/builds/c2QK9cmj/0/digitalization/personal_network_visualization/node_modules/babel-traverse/lib/visitors.js:72:3)
    at traverse (/home/gitlab-runner/builds/c2QK9cmj/0/digitalization/personal_network_visualization/node_modules/babel-traverse/lib/index.js:77:12)
    at NodePath.traverse (/home/gitlab-runner/builds/c2QK9cmj/0/digitalization/personal_network_visualization/node_modules/babel-traverse/lib/path/index.js:144:25)
    at Object.enter (/home/gitlab-runner/builds/c2QK9cmj/0/digitalization/personal_network_visualization/node_modules/istanbul-lib-instrument/dist/visitor.js:611:12)
    at PluginPass.enter (/home/gitlab-runner/builds/c2QK9cmj/0/digitalization/personal_network_visualization/node_modules/babel-plugin-istanbul/lib/index.js:90:23)
    at newFn (/home/gitlab-runner/builds/c2QK9cmj/0/digitalization/personal_network_visualization/node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (/home/gitlab-runner/builds/c2QK9cmj/0/digitalization/personal_network_visualization/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/home/gitlab-runner/builds/c2QK9cmj/0/digitalization/personal_network_visualization/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/home/gitlab-runner/builds/c2QK9cmj/0/digitalization/personal_network_visualization/node_modules/babel-traverse/lib/path/context.js:105:12)
  - code: [undefined]
  - codeFrame: organizational-network-visualizer/adapters/application.js: You gave us a visitor for the node type "ClassPrivateProperty" but it's not a valid type
  - errorMessage: Build Canceled: Broccoli Builder ran into an error with `broccoli-persistent-filter:Babel > [Babel: organizational-network-visualizer]` plugin. 💥
organizational-network-visualizer/adapters/application.js: You gave us a visitor for the node type "ClassPrivateProperty" but it's not a valid type
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: organizational-network-visualizer/adapters/application.js
    - line: [undefined]
    - treeDir: /home/gitlab-runner/builds/c2QK9cmj/0/digitalization/personal_network_visualization/tmp/broccoli_persistent_filterbabel__babel_organizational_network_visualizer-input_base_path-ZosUOwww.tmp
  - message: Build Canceled: Broccoli Builder ran into an error with `broccoli-persistent-filter:Babel > [Babel: organizational-network-visualizer]` plugin. 💥
organizational-network-visualizer/adapters/application.js: You gave us a visitor for the node type "ClassPrivateProperty" but it's not a valid type
  - name: Error
  - nodeAnnotation: Babel: organizational-network-visualizer
  - nodeName: broccoli-persistent-filter:Babel > [Babel: organizational-network-visualizer]
  - originalErrorMessage: organizational-network-visualizer/adapters/application.js: You gave us a visitor for the node type "ClassPrivateProperty" but it's not a valid type
  - stack: Error: organizational-network-visualizer/adapters/application.js: You gave us a visitor for the node type "ClassPrivateProperty" but it's not a valid type
    at verify (/home/gitlab-runner/builds/c2QK9cmj/0/digitalization/personal_network_visualization/node_modules/babel-traverse/lib/visitors.js:196:13)
    at Object.explode (/home/gitlab-runner/builds/c2QK9cmj/0/digitalization/personal_network_visualization/node_modules/babel-traverse/lib/visitors.js:72:3)
    at traverse (/home/gitlab-runner/builds/c2QK9cmj/0/digitalization/personal_network_visualization/node_modules/babel-traverse/lib/index.js:77:12)
    at NodePath.traverse (/home/gitlab-runner/builds/c2QK9cmj/0/digitalization/personal_network_visualization/node_modules/babel-traverse/lib/path/index.js:144:25)
    at Object.enter (/home/gitlab-runner/builds/c2QK9cmj/0/digitalization/personal_network_visualization/node_modules/istanbul-lib-instrument/dist/visitor.js:611:12)
    at PluginPass.enter (/home/gitlab-runner/builds/c2QK9cmj/0/digitalization/personal_network_visualization/node_modules/babel-plugin-istanbul/lib/index.js:90:23)
    at newFn (/home/gitlab-runner/builds/c2QK9cmj/0/digitalization/personal_network_visualization/node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (/home/gitlab-runner/builds/c2QK9cmj/0/digitalization/personal_network_visualization/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/home/gitlab-runner/builds/c2QK9cmj/0/digitalization/personal_network_visualization/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/home/gitlab-runner/builds/c2QK9cmj/0/digitalization/personal_network_visualization/node_modules/babel-traverse/lib/path/context.js:105:12)
```

**Comment by buschtoens** [comment]
@csprocket777 What's the output of:

```bash
yarn list --pattern ember-cli-babel
yarn list --pattern ember-cli-typescript
yarn list --pattern ember-concurrency-decorators
yarn list --pattern @ember-decorators/babel-transforms
```

**Comment by burcuaybak** [comment]
I have the same issue and the output is nothing
